= {lab_name}
include::_attributes.adoc[]

== {ic} 概要

この {ic-lab} では、さまざまな AI/ML テクノロジを組み合わせて、ビジネス上の問題に対する価値あるソリューションを生み出す方法を説明します。

このラボに含まれる情報、コード、モデル、テクニックは、AI 強化アプリケーションの最初のプロトタイプがどのようなものになるかを示したものです。これは、規定された要件に対処する決定的な方法ではありません。

== 免責事項

この {ic-lab} は、お客様が {rhoai} を使用して構築できるものの例です。{rhoai} 自体には、保険金請求処理に関連する特定の機能はありません。

この {ic-lab} では、大規模言語モデル (LLM) と画像処理モデルを使用します。これらのモデルは {rhoai} 製品には含まれていません。この {ic-lab} の利便性のために提供されています。

これらのモデルの品質はプロトタイプには十分です。実稼働環境で使用する適切なモデルを選択することは、多くの実験と調整を必要とする複雑な作業です。この {ic-lab} では、この側面はカバーされていません。

== タイムテーブル

これは発表される資料の暫定的な(参考)タイムテーブルです。

[width="90%",cols="3,^2,^2,10",options="header"]
|=========================================================
| Name |時間 |種類 |説明

|背景 |5 | プレゼンテーション
a|- 望ましい最終状態がどのようなものかを説明します。
- 全体的なユーザー エクスペリエンスと基礎となるアーキテクチャを説明します。
- 視覚化を向上させるためにモックアップを共有します

| 接続とセットアップ | 5 | ハンズオン
a|- 参加者が自身のワークショップ環境に接続します。
- 環境の健全性の検証を行います。
- プロジェクトにアクセスする

|LLM |20 | ハンズオン
a|- 請求文書の要約
- 感情の抽出
- モデル比較と選択
- パイプラインによる全性チェック
- プロンプト エンジニアリング（オプション）

| 画像処理 | 20 | ハンズオン
a|- 車の画像認識
- モデルの再トレーニング
- モデルのサービング

| Web アプリ | 20 | ハンズオン
a|- GitOpsによるサンプルアプリケーションのデプロイ
- 更新
- RAG

|=========================================================


== Contributing

このプロジェクトへの貢献にご興味がある場合は、この GitHub リポジトリを参照してください: https://github.com/RH-OPEN/parasol-insurance/tree/translation-jp [https://github.com/RH-OPEN/parasol-insurance/tree/translation-jp,window=_blank]
